problem docs link: - https://docs.google.com/document/d/1i_RdiQyERSe_1jvptsvjiA6-iO98qjg6jMnIxjbSMGI/edit?tab=t.0#heading=h.daemhubpnz89

### Problem 1 — Scaling head-to-head

In [15]:
import numpy as np
weight = np.array([58, 62, 65, 66, 190])
height = np.array([150, 160, 170, 175, 180])

weight3val = weight[:3]
height3val = height[:3]

weightmean = np.mean(weight3val)
weightstd = np.std(weight3val)

heightmean = np.mean(height3val)
heightstd = np.std(height3val)
print(weightmean)
print(round(weightstd, 2))

weight_standard = (weight3val - weightmean) / weightstd
print(np.round(weight_standard, 2))

print(heightmean)
print(round(heightstd, 2))


height_standard = (height3val - heightmean) / heightstd
print(np.round(height_standard, 2))

61.666666666666664
2.87
[-1.28  0.12  1.16]
160.0
8.16
[-1.22  0.    1.22]


In [16]:
# b) MIN MAX SCALING

weight_sca = (weight - np.min(weight)) / (np.max(weight) - np.min(weight))
height_sca = (height - np.min(height)) / (np.max(height)-np.min(height))

print(np.round(weight_sca, 3))
print(np.round(height_sca, 3))

[0.    0.03  0.053 0.061 1.   ]
[0.    0.333 0.667 0.833 1.   ]


In [17]:
# c) ROBUST SCALING
median = np.median(weight)
q1 = np.percentile(weight, 25)
q3 = np.percentile(weight, 75)
iqr = q3 - q1
print(median)
print(q1)
print(q3)
print(iqr)

robust = (weight-median)/ iqr 
print(np.round(robust, 2))

65.0
62.0
66.0
4.0
[-1.75 -0.75  0.    0.25 31.25]


In [18]:
# d) Conclusion

# Robust Scaling handles outliers best.
# Because it uses Median and IQR instead of Mean and Standard Deviation.
# Median and IQR are less affected by extreme values like 190.

Problem 2 — When to use which scale

In [19]:
import numpy as np

monthly_income = np.array([20000, 22000, 25000, 2000000])
room_tmp = np.array([18, 22, 25, 30])
transaction_cnt = np.array([0,0,1,2,3,50])

# a) SCALER CHOICE (Explanation only)

# Monthly Income → Robust Scaling
# Reason: Outliers (very high income) exist, so median & IQR is safer.

# Room Temperature → Min-Max Scaling
# Reason: Fixed range (18–30), so scaling to 0–1 is meaningful.

# Transaction Count → Standardization
# Reason: Skewed distribution, mean & std helps center data.

In [20]:
# 1. Monthly Income - Robust Scaling

income_median = np.median(monthly_income)
q1 = np.percentile(monthly_income, 25)
q3 = np.percentile(monthly_income, 75)
iqr = q3 - q1

income_robust = (monthly_income-income_median)/iqr

print(income_median)
print(iqr)
print(np.round(income_robust, 2))

23500.0
497250.0
[-0.01 -0.    0.    3.97]


In [21]:
# 2. Room Temperature - Min Max Scaling
tmp_min = np.min(room_tmp)
tmp_max = np.max(room_tmp)
room_minmax = (room_tmp- tmp_min) / (tmp_max - tmp_min)

print(np.round(room_minmax, 2))

[0.   0.33 0.58 1.  ]


In [23]:
# 3. Transaction Count - Standardization
trans_mean = np.mean(transaction_cnt)
trans_std = np.std(transaction_cnt)
transaction_stn = (transaction_cnt - trans_mean) / trans_std
print(round(trans_mean, 2))
print(round(trans_std, 2))
print(np.round(transaction_stn, 2))

9.33
18.22
[-0.51 -0.51 -0.46 -0.4  -0.35  2.23]
