In [4]:
import torch
print(torch.__version__)

2.11.0+cpu


In [5]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is not available


In [6]:
a = torch.empty(2,3)
a

tensor([[2.1715e-18, 1.0387e+21, 4.2295e-05],
        [5.3410e-08, 1.3295e+22, 1.6518e-04]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.1573, 0.2807, 0.1170],
        [0.5367, 0.1680, 0.2023]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor( [[1,2,3], [4,5,6] ] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.arange(0,10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Tensor Shape

In [15]:
x = torch.tensor( [[1,2,3], [4,5,6] ] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[      698623488,       698601136,     38654705665],
        [              0,               8, 139627951565872]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Data Type

In [21]:
x.dtype

torch.int64

In [22]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [23]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [24]:
x = x.to(torch.float32)

In [25]:
x.dtype

torch.float32

### Mathematical Operation

In [26]:
x = torch.tensor( [[1,2,3], [4,5,6]] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [28]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [30]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [31]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [32]:
#floor
x*100

tensor([[100, 200, 300],
        [400, 500, 600]])

In [33]:
x // 3

tensor([[0, 0, 1],
        [1, 1, 2]])

In [34]:
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [35]:
x%2

tensor([[1, 0, 1],
        [0, 1, 0]])

### Element wise operation

In [36]:
a = torch.rand(2,3)
b = torch.rand(2, 3)

In [37]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [38]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [39]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [40]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [41]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [42]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [43]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [44]:
c = torch.tensor( [-1,-2,-3,-4] )

In [45]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [46]:
c = torch.tensor( [1,2,3,4] )

In [47]:
torch.neg(c)

tensor([-1, -2, -3, -4])

In [48]:
d = torch.tensor([1.2, 2.5, 3.5, 4.5])

In [49]:
torch.round(d)

tensor([1., 2., 4., 4.])

In [51]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [52]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [54]:
d = torch.tensor([100, 200, 300, 400])

In [55]:
torch.clamp(d, min=1, max=2)

tensor([2, 2, 2, 2])

### Reduction operation

In [56]:
e = torch.randint(size = (2,3), low=0, high=10, dtype=torch.float32)

In [57]:
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [60]:
torch.sum(e)

tensor(27.)

In [62]:
torch.sum(e, dim=0)

tensor([9., 9., 9.])

In [64]:
torch.sum(e, dim=1)

tensor([10., 17.])

In [65]:
torch.mean(e)

tensor(4.5000)

In [66]:
torch.mean(e, dim = 0)

tensor([4.5000, 4.5000, 4.5000])

In [67]:
torch.median(a)

tensor(0.7565)

In [68]:
#max and min
torch.max(e)

tensor(9.)

In [69]:
torch.min(e)

tensor(0.)

In [70]:
torch.prod(e)

tensor(0.)

In [71]:
torch.std(e)

tensor(4.5935)

In [72]:
torch.var(e)

tensor(21.1000)

In [73]:
# argmin, argmax

torch.argmax(e)

tensor(2)

In [74]:
torch.argmin(e)

tensor(0)

### Matrix Operation

In [75]:
f = torch.randint(size = (2,3), low=0, high=10)
g = torch.randint(size = (2,3), low=0, high=10)

In [79]:
f

tensor([[7, 0, 0],
        [9, 5, 7]])

In [80]:
g

tensor([[3, 9, 4],
        [0, 5, 7]])

In [82]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [83]:
torch.dot(vector1, vector2)

tensor(11)

In [85]:
f

tensor([[7, 0, 0],
        [9, 5, 7]])

In [86]:
f.shape

torch.Size([2, 3])

In [87]:
torch.transpose(f, 0, 1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [88]:
h = torch.randint(size = (3,3), low=0, high=10, dtype=torch.float32)

In [89]:
torch.det(h)

tensor(184.0000)

In [90]:
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

### Comparison Operation

In [91]:
i = torch.randint(size = (2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [92]:
i

tensor([[9, 2, 6],
        [7, 7, 8]])

In [93]:
j

tensor([[3, 6, 1],
        [5, 5, 0]])

In [94]:
# greather than
i > j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [95]:
# Less than
i < j

tensor([[False,  True, False],
        [False, False, False]])

In [96]:
# Equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [97]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

### Special Function

In [98]:
k = torch.tensor([10, 20, 30])
k

tensor([10, 20, 30])

In [104]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [105]:
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [106]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [107]:
#sigmoid
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [108]:
#softmax
torch.softmax(k, dim = 0)

NotImplementedError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

In [109]:
torch.relu(k)

tensor([10, 20, 30])

### inplace Operations

In [110]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [112]:
b = a+b
b

tensor([[2.2239, 4.3023, 6.1784],
        [2.8238, 4.5557, 6.9770]])

In [115]:
m = torch.rand(2.3)
n = torch.rand(2,3)

TypeError: rand(): argument 'size' (position 1) must be tuple of ints, not float

In [117]:
m.add_(n)

NameError: name 'm' is not defined

#### Coppy A Tensor

In [122]:
a = torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [124]:
b = a

In [125]:
b[2] = 30

In [126]:
b

tensor([ 1,  2, 30,  4,  5])

In [127]:
a

tensor([ 1,  2, 30,  4,  5])

In [129]:
b = a.clone()

In [131]:
b

tensor([ 1,  2, 30,  4,  5])

In [132]:
id(a)

139626550256384