In [232]:
arr = [1,2,3]
print(arr * 5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [234]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1 * 5
print(arr1)

[ 5 10 15]


## Ndarray

In [164]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])

# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] # row2
                ])

#3d array
arr3 = np.array([
    #1st floor
    [
        [1,2,3], # row1
        [4,5,6] # row2
    ],
    #2nd floor
    [
        [1,2,3], # row1
        [4,5,6] # row2
    ],  
    #3nd floor
    [
        [1,2,3], # row1
        [4,5,6] # row2
    ]
])


## Array Attributes

In [165]:
# dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


## ndarray data type

In [166]:
arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([1.5, 2,4, 3.2])
print(arr.dtype)

int64
float64


In [167]:
arr = np.array([1,2,3.2])
# upcasting
print(arr.dtype)

# upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)

arr = np.array([1,True,3.25, 'hello'])
print(arr.dtype)

float64
<U32
<U32


# selecting a data type for an array

In [168]:
arr = np.array([1,2,300], dtype=np.int16)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int32)
print(arr.dtype)

# error
arr = np.array([1,2,3.2, 'hello'], dtype=np.float64)



int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

In [ ]:
arr = np.array([1,2,300])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)


## ndarray creation from existion data

In [ ]:
# list
lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)

mixed_lst = [10, True, 'Hello', 10.5]
arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3],
           [4,5,6]]
arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


In [ ]:
# Tuple

tpl = (10,20,30)
arr = np.array(tpl, dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [ ]:
# set

st = {1,2,3}
arr = np.array(list(st))
# print(arr.dtype)
# arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [169]:
# dictionary
dc = {'a' : 10, 'b' : 20, 'c' : 30}

keys = dc.keys()
values = dc.values()
items = dc.items()


In [170]:
# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [171]:
# values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [172]:
# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating ndarray from scratch

In [173]:
# np.zeros
arr = np.zeros((2,3), dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [174]:
# np.ones
arr = np.ones((3,4,3), dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.ones_like(arr3)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [175]:
# np.empty
arr = np.empty((4,3), dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [176]:
# np full
arr = np.full((4,3), np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr =  np.full_like(arr3,np.inf, dtype = np.float64)
print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


In [190]:
# np.random.rand(shape)

arr = np.random.rand(2,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[[0.72805111 0.95313112 0.1239801 ]
 [0.1372176  0.33298607 0.8932374 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [191]:
# np.random.randint(star,end,shape)

arr = np.random.randint(1,10, (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[8 8 4]
 [5 9 1]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [192]:
# np.random.uniform(star,end,shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[[60.79632752 98.75113906 86.42291612 90.42490652]
  [52.6074531  71.95053077 57.54698197 60.9069887 ]
  [60.76049984 79.35949101 63.43547845 81.78463258]]

 [[52.5700389  69.9615598  54.29380529 51.57199164]
  [54.90796646 91.47063518 90.43713173 53.48427471]
  [96.3828041  86.05211311 97.14188195 73.24173966]]

 [[65.29528154 89.1796509  74.36072948 73.10693154]
  [77.81510041 51.65874455 63.44587658 94.92087273]
  [50.88660808 50.44651842 76.4917218  80.87582917]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


 ## array creation with rang functions

In [193]:
# np.arange(first, end, step) -> similar to range function

arr = np.arange(1, 10, 1)
mat  = arr.reshape(3,3)
print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [194]:
# np.linspace(start, end, koita)

arr = np.linspace(0, 4, 6)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [195]:
# np.logspace(start, end(included), koita )
arr = np.logspace(0,4,6, base = 2)
print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra

In [196]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [197]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row, column, k)
mat = np.eye(3,4)
print(mat)
mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## indexing and slicing

In [198]:
# indexing

print(arr1)
print(arr2)
# arr1[2]= 100

# print(arr1)

arr2[0][2] = 100
print(arr2[0][2])


[  1   2 100   4   5]
[[  1   2 100]
 [  4   5   6]]
100


In [206]:
# slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2

arr1_mod[2] = 200
print(arr1_mod)
print(arr1)


[  2 100 200]
[  1   2 100   4   5]


In [200]:
#2d slicking
#arr[row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

# getting a row

row_0 = arr2[0:1, ]
row_1 = arr2[1:,]

# print(row_0)
# print(row_1)

# getting a column
col_0 = arr2[::, 0:1]
col_1 = arr2[::, 1:2]
print(col_0)
print(col_1)


#getting a portion
portion = arr2[:: , 0:2]
print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


## Advanced Indexing

In [209]:
lst = np.array([ 10 , 20, 30, 40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [216]:
print(arr2)

print(arr2[[0,1], [1, 2]])

# boolean kono kichu diye
arr2[arr2>2] = 0
print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[[1 2 0]
 [0 0 0]]


In [217]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [228]:
arr = np.array([[10, 20, 30], [100, 200, 300]])

#iteration
for i in np.nditer(arr):
    print(i)

10
20
30
100
200
300


1
