In [2]:
import numpy as np

arr = np.random.randint(1, 100, size = (10, 5)) # sample - 10 , feature - 5


In [3]:
arr.shape

(10, 5)

In [4]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[98, 73, 27, 92, 14, 89,  8, 40,  5, 43],
       [32, 38, 63, 63, 59, 21, 98, 89, 52, 16],
       [19, 81, 49, 86, 30, 29, 95, 17, 47, 37],
       [71, 91, 53, 64,  7, 50, 50, 77, 20, 69],
       [72,  1, 77, 18, 94, 17, 57, 60, 77, 10]], dtype=int32)

In [5]:
flatten = b.flatten()

print(flatten.ndim)
flatten
column_wise_flattening = np.ravel(b, order= 'C')
print(column_wise_flattening)

1
[98 73 27 92 14 89  8 40  5 43 32 38 63 63 59 21 98 89 52 16 19 81 49 86
 30 29 95 17 47 37 71 91 53 64  7 50 50 77 20 69 72  1 77 18 94 17 57 60
 77 10]


In [6]:
a = np.random.randint(1, 100, size =(2,3))
b = np.random.randint(20, 30, size =(2,3))
print(a)
print(b)

[[73 61 28]
 [10 96 64]]
[[20 20 26]
 [23 24 20]]


## Concatenate

In [7]:
con_row = np.concatenate((a,b), axis=0) # row wise
print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[73 61 28]
 [10 96 64]
 [20 20 26]
 [23 24 20]]
[[73 61 28 20 20 26]
 [10 96 64 23 24 20]]


In [8]:
# error

# row wais concatenate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1,10, size = (2,3))
y = np.random.randint(1, 10, size = (1,3))

r = np.concatenate((x,y), axis = 0)
r = np.concatenate((x,y), axis = 1)

print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [10]:
# transpose 

mat = np.array([[10,20,30], [30,40,50]])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [18]:
# array split

a = np.random.randint(1, 10, size= (10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3)

[7 2 6 4 9 7 6 7 4 5]
[array([7, 2, 6, 4], dtype=int32), array([9, 7, 6], dtype=int32), array([7, 4, 5], dtype=int32)]


ValueError: array split does not result in an equal division

## arithmetic operator and mathematical function

In [38]:
# faster for vactorization

x = np.array([10, 8, 30, 100])
y = np.array([2, 3, 4, 5])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x%y
print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [39]:
# mathematical funiton

# trigonmetry

# sin , cos, tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad


[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [42]:
# log

x = np.array([10, 8, 30, 100])
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.47712125 2.        ]
[3.32192809 3.         4.9068906  6.64385619]
[ 3.16227766  2.82842712  5.47722558 10.        ]


In [44]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul = np.cumulative_sum(x)
print(cumul)

148
[ 10  18  48 148]


In [50]:
# BoardCasting
x = np.array([10, 8, 16, 100 ])

result = x + 2
print(result)

# rulings = columns er size and vector er size same hote hobe
matrix = np.array([[10,20,30],
               [30, 40, 50]
               ])
result = matrix + 2

vector = np.array([1,2,3,4])
result = matrix + vector
print(result)


[ 12  10  18 102]


ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

## Logical Function

In [56]:
# Comparison - >,<, >=, <=, ==, !=

x = np.array([10, 8, 30, 100])
y = np.array([2, 3, 4, 5])

greater_than = x>y
print(greater_than)

equal = x == y
print(equal)

# all () -> shob true kina
# any() -> jekono akta ture ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True  True  True]
[False False False False]
True
False


## Sorting

In [57]:
#inplace
x = np.array([10, 8, 16, 100])
z = x.copy()
print(z)

z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [58]:
# copy sorting

print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [60]:
 # 2d array sorting

mat = np.array([[10, 3, 5], [8,4,9]])

# horizon axis = 1
hor_sort = np.sort(mat, axis=1)
print(hor_sort)

vert_sort = np.sort(mat, axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [61]:
print(x)

[ 10   8  16 100]


In [69]:
# np.where ( condition, x, y) if true x , otherwise replace with y

index = np.where(x == 8) # returns index
print(index)

arr = np.where(x>8, x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [70]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [74]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8, mat, 0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [80]:
x = np.array([10, 100, 8, 16, 100])

maximum_value_index = np.argmax(x)
minimum_value_index = np.argmin(x)

print(maximum_value_index)
print(minimum_value_index)

1
2


## Counting in ndarray

In [87]:
a = np.random.randint(1, 100, size = (100,))
print(a)

[91 11 86 77  2 29 43 89 67 83 36 16 59 21 60  3 95 81 46 92 25  8 33 56
 46 25 13 11 40 74 32 11 85 35 25  9 73 55 59 19 71 15 85 53 40 75 76 84
 65 55 65 45 64 55 64 68 49 42 34  2 36 91 59 63 46 91 40 95 80 91 73 26
 83 93 69 11 56 40 32 14 11  3 79 11 46  4 65 93 28 70 84  4 73 21 40 75
 94 63 58 12]


In [105]:
value_greater_than_60 = np.count_nonzero(a<40)
print(value_greater_than_60)

35


In [108]:
unique_value,count = np.unique(a,return_counts= True)
print(unique_value)
print(count)

[ 2  3  4  8  9 11 12 13 14 15 16 19 21 25 26 28 29 32 33 34 35 36 40 42
 43 45 46 49 53 55 56 58 59 60 63 64 65 67 68 69 70 71 73 74 75 76 77 79
 80 81 83 84 85 86 89 91 92 93 94 95]
[2 2 2 1 1 6 1 1 1 1 1 1 2 3 1 1 1 2 1 1 1 2 5 1 1 1 4 1 1 3 2 1 3 1 2 2 3
 1 1 1 1 1 3 1 2 1 1 1 1 1 2 2 2 1 1 4 1 2 1 2]


## statistical function

In [118]:
#data load
data = np.genfromtxt('student_scores.csv', delimiter = ',', skip_header = 1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [128]:
# statistics

math_marks = data[::, :1]
print(math_marks.T)

max_math_marks = np.max(math_marks)

print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

avarage_math_marks = np.mean(math_marks)
print(avarage_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)


[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [130]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])
correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## Linear Algebra

In [137]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe

dot_product = np.dot(A,B)
print(dot_product)

# trace
print(np.trace(B))


[[ 58  64]
 [139 154]]
17


In [140]:
sq_mat = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]
         ])
det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)
print(det_of_sq)

print(det_of_sq)

-9.51619735392994e-16
-9.51619735392994e-16


In [144]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)

(2, 3)


In [147]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]
