#### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.


In [7]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

print("1D Dimention",arr1.ndim)
print("1D shape", arr1.shape)

#2D array
arr2 = np.array([[1,2,3],
                 [4,5,6]
                ])

print("2D Dimention",arr2.ndim)
print("2D shape", arr2.shape)

#3D array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])

print("3D Dimention",arr3.ndim)
print("3D shape", arr3.shape)

1D Dimention 1
1D shape (5,)
2D Dimention 2
2D shape (2, 3)
3D Dimention 3
3D shape (3, 2, 3)


### 2 . Create:
#### an array of zeros of shape (3,3)
#### an array of ones of shape (2,5)
#### an array filled with 7


In [17]:
zero_shape_arr = np.zeros((3,3))
print(zero_shape_arr)

ones_shape_arr = np.ones((2,5))
print(ones_shape_arr)

fixed_arr = np.full((3,3),7)
print(fixed_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


#### 3 . Create an array of even numbers between 10 and 50 using arange.


In [21]:
even_array = np.arange(10,50,2)
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### 4 . Create a 4×4 matrix from 0–15. Then , extract:
#### the first row
#### the last column
#### a 2×2 subarray from the center

In [22]:
matrix_arr = np.arange(16).reshape(4,4)
print("Matrix: \n", matrix_arr)

fst_row = matrix_arr[0]
print("First row: ",fst_row)

lst_col = matrix_arr[:, -1]
print("Last column:", lst_col)

mid = matrix_arr[1:3, 1:3]
print("Center 2x2\n",mid)

Matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
First row:  [0 1 2 3]
Last column: [ 3  7 11 15]
Center 2x2
 [[ 5  6]
 [ 9 10]]


#### 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.


In [24]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
arr = np.array([1,2,3])
ans = matrix + arr
print(ans)


[[11 22 33]
 [41 52 63]
 [71 82 93]]


#### 6 . Given two arrays A and B, compute:
#### (A + B) / 2
#### A**2 + B**2


In [ ]:
arrA = np.array([1,2,3])

arrB = np.array([1,2,3])

fst_ans = (arrA + arrB)/2

scnd_ans = (arrA**2 + arrB**2)

print(fst_ans)
print(scnd_ans)


[1. 2. 3.]
[ 2  8 18]
