## 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.


In [7]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

print("1D Dimention",arr1.ndim)
print("1D shape", arr1.shape)

#2D array
arr2 = np.array([[1,2,3],
                 [4,5,6]
                ])

print("2D Dimention",arr2.ndim)
print("2D shape", arr2.shape)

#3D array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])

print("3D Dimention",arr3.ndim)
print("3D shape", arr3.shape)

1D Dimention 1
1D shape (5,)
2D Dimention 2
2D shape (2, 3)
3D Dimention 3
3D shape (3, 2, 3)


In [17]:
zero_shape_arr = np.zeros((3,3))
print(zero_shape_arr)

ones_shape_arr = np.ones((2,5))
print(ones_shape_arr)

fixed_arr = np.full((3,3),7)
print(fixed_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [21]:
even_array = np.arange(10,50,2)
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
