### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', "Unnamed: 32"], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


### Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [12]:
len(df.columns)

31

In [13]:
len(X_train) + len(X_test)

569

In [14]:
X_train

array([[-0.80269427, -0.38286221, -0.81924372, ..., -0.43211439,
         0.11483085, -0.37537238],
       [ 0.88529183,  1.85508297,  0.8377345 , ...,  0.63880159,
         0.17507133,  0.40517221],
       [-1.23236346, -0.26839529, -1.15697449, ..., -0.24268792,
        -0.46966465,  1.92471149],
       ...,
       [-0.20068524,  0.3062754 , -0.12794436, ...,  1.41401222,
         1.11124101,  1.61011937],
       [-0.47513054, -0.14224807, -0.45112146, ..., -0.20517773,
         0.18158382,  0.2211655 ],
       [-0.99451087,  0.27590662, -0.94723041, ..., -0.44743105,
        -0.48431774,  0.19208057]])

In [15]:
y_train

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,

In [16]:
X_train

array([[-0.80269427, -0.38286221, -0.81924372, ..., -0.43211439,
         0.11483085, -0.37537238],
       [ 0.88529183,  1.85508297,  0.8377345 , ...,  0.63880159,
         0.17507133,  0.40517221],
       [-1.23236346, -0.26839529, -1.15697449, ..., -0.24268792,
        -0.46966465,  1.92471149],
       ...,
       [-0.20068524,  0.3062754 , -0.12794436, ...,  1.41401222,
         1.11124101,  1.61011937],
       [-0.47513054, -0.14224807, -0.45112146, ..., -0.20517773,
         0.18158382,  0.2211655 ],
       [-0.99451087,  0.27590662, -0.94723041, ..., -0.44743105,
        -0.48431774,  0.19208057]])

In [17]:
type(y_train)

numpy.ndarray

In [18]:
type(y_test)

numpy.ndarray

### Numpy Array to tensors

In [19]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_923/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_923/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_923/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_923/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommend

In [20]:
type(X_train_tensor)

torch.Tensor

### Dataset and Dataloader

In [21]:
from torch.utils.data import Dataset,DataLoader

In [22]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [23]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [24]:
len(train_dataset)

455

In [25]:
train_dataset[2]

(tensor([-1.2324, -0.2684, -1.1570, -1.0239,  0.0519,  0.5025,  0.5636, -0.2990,
         -0.5106,  2.7054,  0.1398,  2.0517,  0.1750, -0.2516,  1.9813,  3.5083,
          2.8055,  2.0803,  2.1782,  5.1136, -1.0599, -0.1958, -1.0415, -0.8721,
         -0.1102,  0.2684,  0.3744, -0.2427, -0.4697,  1.9247]),
 tensor(0.))

### loader

In [26]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

### Defining the Model

In [27]:
import torch.nn as nn

In [29]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [30]:
torch.rand(30, 1)

tensor([[0.6634],
        [0.2940],
        [0.7825],
        [0.7880],
        [0.9944],
        [0.5097],
        [0.2971],
        [0.3496],
        [0.6001],
        [0.2708],
        [0.4452],
        [0.4296],
        [0.4735],
        [0.1736],
        [0.7500],
        [0.7929],
        [0.7890],
        [0.8197],
        [0.4691],
        [0.1686],
        [0.1893],
        [0.0948],
        [0.3690],
        [0.3929],
        [0.3704],
        [0.6185],
        [0.3326],
        [0.3936],
        [0.0762],
        [0.4959]])

### Parameters

In [31]:
X_train_tensor.shape[1]

30

In [33]:
learning_rate = 0.1
epochs = 25

In [34]:
loss_function = nn.BCELoss()

In [35]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [36]:
model = MySimpleNN(X_train_tensor.shape[1])

In [37]:
model.parameters()

<generator object Module.parameters at 0x7c611f4b5d20>

In [38]:
X_test_tensor.dtype

torch.float32

In [39]:
model.linear.weight.dtype

torch.float32

In [40]:
y_train_tensor.dtype

torch.float32

In [41]:
model.parameters()

<generator object Module.parameters at 0x7c611142b920>

### Training Pipeline

In [42]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.23380526900291443 
 2 , Loss = 0.07331844419240952 
 3 , Loss = 0.1928839385509491 
 4 , Loss = 0.057098113000392914 
 5 , Loss = 0.17197145521640778 
 6 , Loss = 0.2760000228881836 
 7 , Loss = 0.10804980993270874 
 8 , Loss = 0.09554020315408707 
 9 , Loss = 0.04890429228544235 
 10 , Loss = 0.037967365235090256 
 11 , Loss = 0.05487203225493431 
 12 , Loss = 0.05311053246259689 
 13 , Loss = 0.06604135781526566 
 14 , Loss = 0.07848178595304489 
 15 , Loss = 0.40677085518836975 
 16 , Loss = 0.029032187536358833 
 17 , Loss = 0.1028699204325676 
 18 , Loss = 0.057212408632040024 
 19 , Loss = 0.11282285302877426 
 20 , Loss = 0.24179795384407043 
 21 , Loss = 0.010971973650157452 
 22 , Loss = 0.13521260023117065 
 23 , Loss = 0.06009645015001297 
 24 , Loss = 0.007811087183654308 
 25 , Loss = 0.07091421633958817 


### Training pipeline version 2

In [44]:
# Create model
model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))

    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 6

### Model Evaluation (old)

In [45]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5340104699134827


### Better Version

In [46]:
y_pred.shape

torch.Size([114, 1])

In [47]:
batch_labels.shape

torch.Size([7])

In [48]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)


0.9861111044883728


In [49]:
accuracy_list

[1.0, 1.0, 1.0, 0.9444444179534912]

# Summary

In [50]:
X_train_tensor.shape

torch.Size([455, 30])

In [51]:
!pip install torchinfo

In [52]:
from torchinfo import summary

In [53]:
summary(model, input_size = (455,30))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06