In [75]:
!pip install nltk

In [76]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter # Counts frequency of elements in a list or text.
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize #Splits text into individual words/tokens.
import nltk #Used for NLP tasks like tokenization, stemming, stopword removal, etc

In [77]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [78]:
# NLTK does NOT come with pretrained tokenizers by default.

#Tokenization
nltk.download('punkt')

#Some newer NLTK versions require additional tokenizer tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

### Tokenize

In [79]:
tokens = word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

### Build vocabs

In [80]:
#build vocab
vocab = { '<unk>' : 0 }

In [81]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)
vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [82]:
len(vocab)

284

### Extract sentence from data

In [83]:
input_sentences = document.split('\n')

In [84]:
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [85]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [86]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))


In [87]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

### Training Sequence form

In [88]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1, len(sentence)):
     training_sequence.append(sentence[:i+1])

In [89]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [90]:
len(training_sequence)

555

In [91]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [92]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

In [93]:
max(len_list)

25

### Padding

In [94]:
# logic
[0]* (max(len_list) - len(sequence))

[]

In [95]:
training_sequence[0]

[1, 2]

In [96]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append([0]* (max(len_list) - len(sequence)) + sequence)

In [97]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [98]:
padded_training_sequence[6]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9]

### Tensor Convert

In [99]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [100]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [101]:
X = padded_training_sequence[:, :-1]

In [102]:
y = padded_training_sequence[:, -1]

In [103]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [104]:
len(X)

555

In [105]:
len(y)

555

### Custom Dataset and Dataloader

In [106]:
class CustomDataset(Dataset):
  def __init__(self, X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]
  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]


In [107]:
dataset = CustomDataset(X,y)

In [108]:
len(dataset)

555

In [109]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [110]:
for input, output in dataloader:
  print(input, output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 135,  27],
        [  0,   0,   0,   0,   0,   0,   0,  38,   1,   3, 268, 145, 146,  10,
          11, 269,   5,   1,  44, 270,   1, 240, 271,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0, 239, 254,  10, 153, 255],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0, 135,  27, 136,  43],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,  11, 184],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 238, 239, 240,  10,   1,   3],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,  11, 266,  50,  76,  75],
        [  0,   0,   0,   0

In [111]:
X.shape

torch.Size([555, 24])

In [112]:
y.shape

torch.Size([555])

In [113]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [114]:
X[554]

tensor([158, 223,  10,  11, 278, 281, 282, 139, 283,   8,   4,  50,   1, 172,
        171, 131, 153,   5,   1,   2,   3,  40,   1,  41])

In [115]:
X[555] # 555 newa jabe na

IndexError: index 555 is out of bounds for dimension 0 with size 555

In [116]:
len(dataset)

555

In [117]:
len(vocab)

284

In [118]:
len(dataset[0])

2

In [119]:
len(dataset[0][0])

24

In [120]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

### LSTM Cell

In [151]:
class LSTMModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150, vocab_size)
  def forward(self, X):
    embedded = self.embedding(X)
    intermediate_hidden_states,(final_hidden_states, final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_states.squeeze(0))
    return output

In [152]:
model = LSTMModel(len(vocab))

In [123]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [124]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [125]:
len(vocab)

284

In [126]:
x = nn.Embedding(284, 100)
y = nn.LSTM(100, 150, batch_first=True)
z = nn.Linear(150, 284)

In [127]:
len(dataset)

555

In [128]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [129]:
dataset[0][0].shape

torch.Size([24])

In [130]:
a = dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [131]:
x(a)

tensor([[[-1.2630, -0.1276,  0.0980,  ..., -1.1204,  0.9321, -0.7074],
         [-1.2630, -0.1276,  0.0980,  ..., -1.1204,  0.9321, -0.7074],
         [-1.2630, -0.1276,  0.0980,  ..., -1.1204,  0.9321, -0.7074],
         ...,
         [-1.2630, -0.1276,  0.0980,  ..., -1.1204,  0.9321, -0.7074],
         [-1.2630, -0.1276,  0.0980,  ..., -1.1204,  0.9321, -0.7074],
         [ 1.2866, -1.4366, -0.5282,  ...,  1.0367,  0.9705, -0.1837]]],
       grad_fn=<EmbeddingBackward0>)

In [132]:
x(a).shape

torch.Size([1, 24, 100])

In [133]:
b = x(a)

In [134]:
y(b)

(tensor([[[ 0.0096,  0.0446, -0.0561,  ...,  0.1036,  0.0791, -0.0171],
          [-0.0014,  0.0600, -0.0857,  ...,  0.1349,  0.1364, -0.0387],
          [-0.0143,  0.0656, -0.1008,  ...,  0.1425,  0.1733, -0.0558],
          ...,
          [-0.0427,  0.0679, -0.1142,  ...,  0.1333,  0.2302, -0.0959],
          [-0.0428,  0.0679, -0.1142,  ...,  0.1332,  0.2302, -0.0959],
          [-0.2432,  0.0008,  0.0065,  ..., -0.0684,  0.0680, -0.0113]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-0.2432,  0.0008,  0.0065, -0.0167,  0.0053, -0.0124,  0.1607,
            -0.0304, -0.0072, -0.0370,  0.1576, -0.1170, -0.0878,  0.1682,
            -0.3142,  0.1884,  0.0380, -0.0847, -0.1010,  0.0053, -0.3131,
             0.1974, -0.3309, -0.0546,  0.2566,  0.1126, -0.2002, -0.0750,
            -0.0579, -0.1626, -0.2226, -0.1299,  0.0336,  0.0261, -0.0197,
             0.0797, -0.0026, -0.0652, -0.1716, -0.1836, -0.0620, -0.0179,
             0.0980, -0.0665,  0.1182,  0.0561, -0.1258,  0.10

In [135]:
len(y(b))

2

In [136]:
c, d = y(b)

In [138]:
c.shape

torch.Size([1, 24, 150])

In [139]:
len(y(b))

2

In [140]:
len(d)

2

In [141]:
e, f=d

In [142]:
e.shape #Cell state

torch.Size([1, 1, 150])

In [143]:
f.shape

torch.Size([1, 1, 150])

In [145]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

In [146]:
f_temp = f.squeeze(0)

In [147]:
z(f_temp)

tensor([[ 0.1112,  0.0432, -0.1862, -0.1841,  0.3022,  0.1452,  0.1128,  0.4746,
         -0.1398,  0.1468,  0.0031, -0.0987,  0.0297,  0.0365,  0.2316,  0.0333,
         -0.1154, -0.2309,  0.1623,  0.1706, -0.3815,  0.2500, -0.1146, -0.0387,
          0.2964,  0.2152, -0.0932,  0.1610,  0.1029, -0.3233, -0.0496, -0.1572,
         -0.1002,  0.2324,  0.0663, -0.1347, -0.2059, -0.0056, -0.1119,  0.3323,
         -0.1478, -0.1207, -0.3014,  0.0695,  0.1079,  0.3618, -0.3389,  0.1802,
         -0.3191, -0.0364,  0.1427,  0.0698,  0.3680,  0.0648,  0.0860,  0.0609,
         -0.2032,  0.1566,  0.0849,  0.0797, -0.3205, -0.2510,  0.0461,  0.2052,
         -0.0694, -0.1498, -0.0914,  0.2449,  0.2202, -0.0185, -0.1854,  0.1177,
          0.1036, -0.2120, -0.0692,  0.2067, -0.0985,  0.0087, -0.0188, -0.0788,
          0.1015, -0.0474,  0.1428, -0.0454, -0.1862, -0.1405,  0.0805, -0.1623,
         -0.0212,  0.0095, -0.0625,  0.2184, -0.1266, -0.2548,  0.1211, -0.1046,
         -0.0796,  0.0476, -

In [148]:
len(f_temp[0])

150

In [149]:
len(z(f_temp)[0])

284

In [150]:
len(vocab)

284

In [157]:
for batch_X, batch_y  in dataloader:
  print(batch_X, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 116,
           6, 117, 118, 119, 120, 121, 122, 123,   6,  18],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,  28, 227,
          56, 228,  38,  59, 229,  22, 230, 231,   1, 205],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   1, 214, 215, 216],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,  38,   1,   3, 268, 145, 146],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0, 125, 126, 127,  10,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,  62],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0, 239, 254,  10, 153, 255,  11,   6],
        [  0,   0,   0,   0

### Training loop

In [154]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()

In [155]:
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [159]:
#training loop
for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:
    batch_X, batch_y = batch_x.to(device), batch_y.to(device)
    optimizer.zero_grad()
    output = model(batch_x)
    loss = criterion(output, batch_y)

    loss.backward()
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f" Epoch {epoch+1}, Loss = {total_loss:.4f}")


 Epoch 1, Loss = 2.4491
 Epoch 2, Loss = 2.4155
 Epoch 3, Loss = 2.5242
 Epoch 4, Loss = 2.2973
 Epoch 5, Loss = 2.2650
 Epoch 6, Loss = 2.1866
 Epoch 7, Loss = 2.2271
 Epoch 8, Loss = 2.1463
 Epoch 9, Loss = 2.2435
 Epoch 10, Loss = 2.0608
 Epoch 11, Loss = 2.0850
 Epoch 12, Loss = 2.0032
 Epoch 13, Loss = 2.1065
 Epoch 14, Loss = 1.9170
 Epoch 15, Loss = 1.9500
 Epoch 16, Loss = 1.9520
 Epoch 17, Loss = 1.8603
 Epoch 18, Loss = 1.9746
 Epoch 19, Loss = 1.9187
 Epoch 20, Loss = 2.1235
 Epoch 21, Loss = 2.0643
 Epoch 22, Loss = 1.8447
 Epoch 23, Loss = 1.7624
 Epoch 24, Loss = 1.7642
 Epoch 25, Loss = 1.7197
 Epoch 26, Loss = 1.7587
 Epoch 27, Loss = 1.7576
 Epoch 28, Loss = 1.7587
 Epoch 29, Loss = 1.6580
 Epoch 30, Loss = 1.7734
 Epoch 31, Loss = 1.6938
 Epoch 32, Loss = 1.8932
 Epoch 33, Loss = 1.6379
 Epoch 34, Loss = 1.7630
 Epoch 35, Loss = 1.6653
 Epoch 36, Loss = 1.7221
 Epoch 37, Loss = 1.5961
 Epoch 38, Loss = 1.7093
 Epoch 39, Loss = 1.6583
 Epoch 40, Loss = 1.6831
 Epoch 41

### Prediction

In [166]:
max(len_list)

25

In [ ]:
#logic
[0]* (25-len(numerical_text)) + numerical_text

In [182]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)


  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)


  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]


In [188]:
prediction(model,vocab,"Hi how are you the station was")

'Hi how are you the station was nearly'

In [185]:
len(vocab)

284

In [186]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

### Generate Automatically

In [193]:
import time
num_tokens = 20
input_text = 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

### Accuracy Calculation

In [201]:
def calculate_accuracy(model,dataloader,device):

  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      # print(len(batch_x)),len(batch_y)
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      #get model prediction
      output = model(batch_x)

      # print(len(output[0]))

      #get the predictec word indices

      _, predicted = torch.max(output,dim=1)

      # print("printing predicted",predicted)

      #compare wityh actual label

      # print("printing y lable",batch_y)

      # print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

      # print(correct)
      # print("working with total",batch_y.size())
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

In [203]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 96.94%
