**Email Address:- tamimaziz2007@gmail.com**

In [56]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


## Answer to the Q1

In [57]:
age = np.array(ages)
salary = np.array(salaries)

print(age)
print(salary)

print(age.dtype)
print(age.ndim)
print(age.shape)
print(age.size)

print(salary.dtype)
print(salary.ndim)
print(salary.shape)
print(salary.size)

[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10
int64
1
(10,)
10


## Answer to the Q2

In [58]:
salary = np.array(salaries)
age = np.array(ages)

print(np.max(salary))
print(np.min(salary))
print(np.mean(salary))
print(np.mean(age))

89735
30769
57446.9
38.5


## Answer to the Q3

In [59]:
age = np.array(ages)
age_greater = age>30
print(age_greater)
cnt = np.sum(age_greater)
print(cnt)

[ True  True  True False  True  True  True  True False False]
7


## Answer to the Q4

In [60]:
age = np.array(ages)
print(age)
new_age = age+5
print(new_age)

[56 46 32 25 38 56 36 40 28 28]
[61 51 37 30 43 61 41 45 33 33]


## Answer to the Q5

In [61]:
salary = np.array(salaries)
total_salary = np.sum(salary)

max_salary = np.max(salary)
min_salary = np.min(salary)
difference_salary = max_salary - min_salary

print(total_salary)
print(difference_salary)

574469
58966


## Answer to the Q6

In [62]:
import pandas as pd
df = pd.read_csv('employees.csv')

print(df.head(5))
df.info()
df.describe()

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


,id,age,salary
count,10.00000,10.00000,10.000000
mean,5.50000,38.50000,57446.900000
std,3.02765,11.16791,24357.262884
min,1.00000,25.00000,30769.000000
25%,3.25000,29.00000,33152.500000
50%,5.50000,37.00000,58556.500000
75%,7.75000,44.50000,76426.000000
max,10.00000,56.00000,89735.000000


## Answer to the Q7

In [63]:
print(df[['id','age','salary']].tail(3))

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


## Answer to the Q8

In [64]:
it_emply = df[df['dept'] == 'IT']
print(it_emply)

print(len(it_emply))

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


## Answer to the Q9

In [65]:
sort_val = df.sort_values('salary', ascending=False)
top_val = sort_val[['salary','dept','age']].head(3)

print(top_val)

   salary     dept  age
6   89735  Finance   36
7   86101       IT   40
0   77191       HR   56


## Answer to the Q10

In [66]:
df.loc[df['salary'] > 80000, 'salary'] = 80000

average_salary = df['salary'].mean()
print(average_salary)

55863.3
